# Generated by Django 4.0.4 on 2022-04-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_category', models.CharField(choices=[('INQ', '문의 등록'), ('ACC', '접수 완료'), ('ANS', '답변 완료')], default='INQ', editable=False, max_length=10, verbose_name='상태')),
                ('title_category', models.CharField(choices=[('GE', '일반'), ('AC', '계정'), ('ET', '기타')], default='GE', max_length=10, verbose_name='질문 카테고리')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('email', models.CharField(max_length=50, verbose_name='이메일')),
                ('email_checkbox', models.BooleanField(default=False, verbose_name='이메일 수신 여부')),
                ('phone', models.CharField(max_length=15, verbose_name='전화번호')),
                ('phone_checkbox', models.BooleanField(default=False, verbose_name='문자 수신 여부')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('generators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators_inquiry', to=settings.AUTH_USER_MODEL)),
                ('last_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier_inquiry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='제목')),
                ('question_category', models.CharField(choices=[('GE', '일반'), ('AC', '계정'), ('ET', '기타')], default='GE', max_length=2, verbose_name='카테고리')),
                ('answer', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('generators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators_faq', to=settings.AUTH_USER_MODEL)),
                ('last_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier_faq', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답변 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('generators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators_answer', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('last_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
